### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by boom210232** [boom210232/ku-polls#27]
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/Users/boom/opt/anaconda3/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/boom/Desktop/ku-polls/polls/tests.py", line 8, in <module>
    from .models import Question
ImportError: attempted relative import with no known parent package

**Comment by boom210232** [comment]
OK From TA , she prefer to use unit from Django
